# permissions for end users to view resourcetypes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: klaudete
    app.kubernetes.io/managed-by: kustomize
  name: resourcetype-viewer-role
rules:
- apiGroups:
  - klaudete.nubank.com.br
  resources:
  - resourcetypes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - klaudete.nubank.com.br
  resources:
  - resourcetypes/status
  verbs:
  - get
