# permissions for end users to view resources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: klaudete
    app.kubernetes.io/managed-by: kustomize
  name: resource-viewer-role
rules:
- apiGroups:
  - klaudete.nubank.com.br
  resources:
  - resources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - klaudete.nubank.com.br
  resources:
  - resources/status
  verbs:
  - get
