---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - klaudete.nubank.com.br
  resources:
  - resourcedefinitions
  - resourcegroupdefinitions
  - resourcegroups
  - resources
  - resourcetypes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - klaudete.nubank.com.br
  resources:
  - resourcedefinitions/finalizers
  - resourcegroupdefinitions/finalizers
  - resourcegroups/finalizers
  - resources/finalizers
  - resourcetypes/finalizers
  verbs:
  - update
- apiGroups:
  - klaudete.nubank.com.br
  resources:
  - resourcedefinitions/status
  - resourcegroupdefinitions/status
  - resourcegroups/status
  - resources/status
  - resourcetypes/status
  verbs:
  - get
  - patch
  - update
