apiVersion: klaudete.nubank.com.br/v1alpha1
kind: ResourceGroup
metadata:
  labels:
    app.kubernetes.io/name: klaudete
    app.kubernetes.io/managed-by: kustomize
  name: resourcegroup-sample
spec:
  # TODO(user): Add fields here
