apiVersion: klaudete.nubank.com.br/v1alpha1
kind: Resource
metadata:
  labels:
    app.kubernetes.io/name: klaudete
    app.kubernetes.io/managed-by: kustomize
  name: resource-sample
spec:
  # TODO(user): Add fields here
