apiVersion: klaudete.nubank.com.br/v1alpha1
kind: ResourceGroup
metadata:
  name: my-pet-family
  namespace: playground
spec:
  resources:
    - name: firstPet
      metadata:
        name: first-pet
      spec:
        name: first-pet
        alias: first-pet
        description: I'm just a pet. I'm the first one.
        resourceTypeRef: pet
        properties:
          prefix: first-doguinho
        connections:
          - via: belongs-to
            target:
              ref:
                name: tiago-pet-owner
        provisioner:
          resources:
            - name: pulumiStack
              ref:
                apiVersion: pulumi.com/v1
                kind: Stack
                metadata:
                  name: ${resource.metadata.name}-dev
                spec:
                  config:
                    prefix: ${resource.spec.properties.prefix}
                  stack: dev
                  projectRepo: https://github.com/ljtfreitas/iac-experiments
                  repoDir: pulumi/random-pet-yaml
                  branch: just-ideas
                  envRefs:
                    PULUMI_CONFIG_PASSPHRASE:
                      type: Literal
                      literal:
                        value: ""
              readyWhen: ${provisioner.resources.pulumiStack.status?.currentUpdate == nil && last(provisioner.resources.pulumiStack.status?.conditions)?.type == "Ready" && provisioner.resources.pulumiStack.status?.lastUpdate?.state == "succeeded"}
              failedWhen: ${provisioner.resources.pulumiStack.status?.lastUpdate?.state == "failed"}
              outputs: ${provisioner.resources.pulumiStack.status.outputs}
        patches:
          - from: ${provisioner.resources.pulumiStack.status.outputs.name}
            to: status.inventory.properties.name
    - name: secondPet
      metadata:
        name: second-pet
      spec:
        name: second-pet
        alias: second-pet
        description: I'm just a pet. I'm the second one. I'm a brother of ${resources.firstPet.spec.name}
        resourceTypeRef: pet
        properties:
          prefix: second-doguinho
        connections:
          - via: belongs-to
            target:
              ref:
                name: tiago-pet-owner
          - via: is-brother
            target:
              ref:
                name: ${resources.firstPet.metadata.name}
        provisioner:
          resources:
            - name: pulumiStack
              ref:
                apiVersion: pulumi.com/v1
                kind: Stack
                metadata:
                  name: ${resource.metadata.name}-dev
                spec:
                  config:
                    prefix: ${resource.spec.properties.prefix}
                  stack: dev
                  projectRepo: https://github.com/ljtfreitas/iac-experiments
                  repoDir: pulumi/random-pet-yaml
                  branch: just-ideas
                  envRefs:
                    PULUMI_CONFIG_PASSPHRASE:
                      type: Literal
                      literal:
                        value: ""
              readyWhen: ${provisioner.resources.pulumiStack.status?.currentUpdate == nil && last(provisioner.resources.pulumiStack.status?.conditions)?.type == "Ready" && provisioner.resources.pulumiStack.status?.lastUpdate?.state == "succeeded"}
              failedWhen: ${provisioner.resources.pulumiStack.status?.lastUpdate?.state == "failed"}
              outputs: ${provisioner.resources.pulumiStack.status.outputs}
        patches:
          - from: ${provisioner.resources.pulumiStack.status.outputs.name}
            to: status.inventory.properties.name

# // ResourceGroup
# // 2 resources - 1pet and 2pet
# // 2 stacks do Pulumi
# // 2 resources atualizados no inventario
# // secondPet precisa ter uma connection com o firstPet