apiVersion: klaudete.nubank.com.br/v1alpha1
kind: Resource
metadata:
  name: random-pet
  namespace: playground
spec:
  name: random-pet
  alias: random-pet
  description: I'm just a random pet.
  resourceTypeRef: pet
  properties:
    prefix: whatever4
  connections:
    - via: belongs-to
      target:
        ref:
          apiVersion: klaudete.nubank.com.br/v1alpha1
          kind: Resource
          name: tiago-pet-owner
  provisioner:
    resources:
      - name: pulumiStack
        ref:
          apiVersion: pulumi.com/v1
          kind: Stack
          metadata:
            name: ${resource.metadata.name}-dev
          spec:
            stack: dev
            projectRepo: https://github.com/ljtfreitas/iac-experiments
            repoDir: pulumi/random-pet-yaml
            branch: just-ideas
            envRefs:
              PULUMI_CONFIG_PASSPHRASE:
                type: Literal
                literal:
                  value: ""
        readyWhen: ${provisioner.resources.pulumiStack.status?.currentUpdate == nil && last(provisioner.resources.pulumiStack.status?.conditions)?.type == "Ready" && provisioner.resources.pulumiStack.status?.lastUpdate?.state == "succeeded"}
        failedWhen: ${provisioner.resources.pulumiStack.status?.lastUpdate?.state == "failed"}
        outputs: ${provisioner.resources.pulumiStack.status.outputs}
  patches:
    - from: ${provisioner.resources.pulumiStack.status.outputs.name}
      to: status.inventory.properties.petName
